<a href="https://colab.research.google.com/github/Sahil-Sidana/SC_Project/blob/main/SC_Project_Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Question 2
'''Solve the travelling salesman problem using GA. The number of cities is 15. The weight matrix will be given as input, and it represents the distance of each city. After 20
iterations you will stop the algorithm. The number of chromosomes is 15. Output is the sequence of cities to travel by the salesman (best solution given by GA).
You may consider elitism principle and roulette-wheel based selection procedure. You can go for one point crossover and crossover points will randomly selected. Take extra
care so that each city will represent once in the solution.'''

'Solve the travelling salesman problem using GA. The number of cities is 15. The weight matrix will be given as input, and it represents the distance of each city. After 20\niterations you will stop the algorithm. The number of chromosomes is 15. Output is the sequence of cities to travel by the salesman (best solution given by GA).\nYou may consider elitism principle and roulette-wheel based selection procedure. You can go for one point crossover and crossover points will randomly selected. Take extra\ncare so that each city will represent once in the solution.'

In [ ]:
import numpy as np

In [ ]:
def total_weight(temporary_solution, weight_matrix):
    weight = 0
    for i in range(len(temporary_solution) - 1):
        weight+=weight_matrix[temporary_solution[i]][temporary_solution[i + 1]]
    weight += weight_matrix[temporary_solution[-1]][temporary_solution[0]]  # Return to the starting city
    return weight

In [ ]:
def roulette_wheel(population, Objective_f_value):
    probablity = Objective_f_value/sum(Objective_f_value)
    index = np.random.choice(len(population), size=len(population), p=probablity)
    return [population[i] for i in index]

In [ ]:
def crossover(parent1, parent2):
    point_of_crossover = np.random.randint(1, len(parent2))
    # Taking extra care so that each city will represent once in the solution, here i represents the city.
    offspring1 = np.concatenate((parent1[:point_of_crossover], [i for i in parent2 if i not in parent1[:point_of_crossover]]))
    offspring2 = np.concatenate((parent2[:point_of_crossover], [i for i in parent1 if i not in parent2[:point_of_crossover]]))
    return offspring1,offspring2

In [ ]:
def initialize_population(chromosomes,cities):
    initial_population = []
    # Making 15 initial solution set with random permutation of cities
    for i in range(chromosomes):
        temporary = np.random.permutation(cities)
        initial_population.append(temporary)
    return initial_population

In [ ]:
def genetic_algorithm(cities,weight_matrix,iterations,chromosomes):

    initial_population = initialize_population(chromosomes, cities)

    # Now Running the Algorithm 20 times.
    for iteration in range(iterations):

        Objective_f_value = []

        for solution in initial_population:
          Objective_f_value.append(1 / (1+ total_weight(solution, weight_matrix)))

        # Elitism: Select the best chromosome
        best_tour_index = np.argmax(Objective_f_value)
        next_population = [initial_population[best_tour_index]]

        # Roulette-wheel selection and crossover
        population_order = roulette_wheel(initial_population, Objective_f_value)
        # CrossOver Parents based on Roulette wheel selection
        for i in range(0,len(population_order)-1,2):
            # Making crossover b/w parents in the order which Roulette wheel selection has created.
            parent1, parent2 = population_order[i], population_order[i + 1]
            offspring1, offspring2 = crossover(parent1,parent2)
            next_population.extend([offspring1, offspring2])

        population = next_population

    #After all iterations select the best solution, i represents city
    every_weight=[]
    for i in population:
      every_weight.append(total_weight(i, weight_matrix))

    best_solution_index = np.argmin(every_weight)
    final_solution = population[best_solution_index]

    return final_solution

In [ ]:
#Given:
cities = 15
iterations = 20
chromosomes = 15

# Generate a random weight matrix for demonstration purposes The weight matrix will be given as input, and it represents the distance of each city.
weight_matrix = np.random.randint(1, 500, size=(cities, cities))


# Making distance to reach city i from i as 0.
for i in range(cities):
  weight_matrix[i][i]=0

print()
print("         Distance Matrix between Cities        ")
print()
print(weight_matrix)


solution = genetic_algorithm(cities,weight_matrix,iterations,chromosomes)

# Making cities as 1-based indexing to print.
solution = solution+1

# Printing Optimal Solution
print()
print("Optimal Solution:")
print()
for i in range(cities-1):
  print(f"Move from city {solution[i]} --> city {solution[i+1]} with cost {weight_matrix[solution[i]-1][solution[i+1]-1]}")
print(f"Move from city {solution[cities-1]} --> city {solution[0]} with cost {weight_matrix[solution[cities-1]-1][solution[0]-1]}")

# Making cities as 0-based indexing to calculate distance from the matrix.
solution = solution-1
print()
print("Total distance:", total_weight(solution, weight_matrix))


         Distance Matrix between Cities        

[[  0 293 270  22 331 368 471 181  33  77 365 357  67 187 254]
 [414   0 391 194 371 288 275  73 319 344 352 461 464 206 349]
 [329  35   0 188 383 460  64 475 398 183 482  60  65 359  91]
 [449 316 110   0 126 454 361 406 335 400 251 187  98 462  65]
 [447 407 206 394   0 325 201 263 198 339 492 476 319 165 326]
 [292 272 146 255  84   0 125 145  97 285 296 300 449 196 488]
 [453 312 368 264  59 309   0 196 400 174 146 378 247 399 243]
 [385 433  82 370 208   7  48   0   3  50 347  67 470  32 440]
 [292  56 188 286  23 440 288 218   0 334 243 496  48 164 459]
 [116 461  30  68  77  69 217   8 124   0 253 459 429   4 489]
 [462 198 169 161  62 252 172 178 452  97   0 427 427 285 193]
 [ 27 437 286 275 474  63 437 194 443 350 202   0 298 131  84]
 [246 384 222 348 460 373 339  39 332 155 371 143   0  92 357]
 [450 130 185 369  62   1 332 212 369 392 140 257  82   0 335]
 [481 421 407 230 149  19 169 456 344 475  80 393  80  79   0]]

Opt